version: "1"
services:
  ui:
   build:
      context: ./frontend
      dockerfile: Dockerfile.reactUI
   ports:
    - 3000:3000
   container_name: app-ui
   networks:
    -  app-net
   volumes:
    -  ./frontend/src:/frontend/app/src
    -  ./frontend/public:/frontend/app/public
   depends_on:
    - api
   stdin_open: true
   tty: true    
  
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.express
    ports:
      - 3001:3001
    container_name: app-api
    networks:
      - app-net
    volumes:
      - ./backend:/backend
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - app-net
    volumes:
      - mongo-data:/data/db
  
networks:
  app-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local